/* eslint-disable import/no-anonymous-default-export */
import img from "../img/products/f1.jpg"

const data = {
  products: [
    {
      _id: "1",
      name: "Multi coloured classi shirt",
      category: "Shirts",
      image: {img},
      price: "250",
      brand: "Botegga",
      stars: 4.8,
      numReviews: 29,
      inStock: 40,
    },
    {
      _id: "2",
      name: "Green Leafy classic shirt",
      category: "Shirts",
      image: "../img/products/f2.jpg",
      price: "300",
      brand: "Gucci",
      stars: 4.5,
      numReviews: 19,
      inStock: 30,
    },
    {
      _id: "3",
      name: "Multi Cool Classic shirt",
      category: "Shirts",
      image: "../img/products/f3.jpg",
      price: "1,250",
      brand: "Rabba",
      stars: 4.7,
      numReviews: 15,
      inStock: 30,
    },
    {
      _id: "4",
      name: "White coloured classic shirt",
      category: "Shirts",
      image: "../img/products/f4.jpg",
      price: "200",
      brand: "Mola",
      stars: 4.0,
      numReviews: 11,
      inStock: 10,
    },
    {
      _id: "5",
      name: "Dream coloured classic shirt",
      category: "Shirts",
      image: {img},
      price: "250",
      brand: "Baetiba",
      stars: 4.7,
      numReviews: 79,
      inStock: 50,
    },
    {
      _id: "6",
      name: "Multi coloured classic shirt",
      category: "Shirts",
      image: "../img/products/f6.jpg",
      price: "350",
      brand: "Botegga",
      stars: 4.9,
      numReviews: 29,
      inStock: 40,
    },
    {
      _id: "7",
      name: "Free flow classic pants",
      category: "Pants",
      image: "../img/products/f7.jpg",
      price: "140",
      brand: "Bogga",
      stars: 4.2,
      numReviews: 19,
      inStock: 20,
    },
    {
      _id: "8",
      name: "Oldie Vibe classic Ladies shirt",
      category: "Female Shirts",
      image: "../img/products/f8.jpg",
      price: "250",
      brand: "Channel",
      stars: 4.8,
      numReviews: 7,
      inStock: 30,
    },
  ],
};
export default data;
